// src/elven/src/views/articles/index.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { push } from "svelte-spa-router";
  import { querystring } from "svelte-spa-router";
  // ui
  import Overlay from "@/components/overlay.svelte";
  import Pagination from "@/components/pagination.svelte";
  import Toolbar from "@/components/toolbar.svelte";
  import ToolbarBig from "@/components/toolbar_big.svelte";
  // article
  import type { Article, Params } from "@/types/articles";
  import { Show, By, Start } from "@/types/articles";
  import type { Meta } from "@/types";
  import CArticle from "../../components/article.svelte";
  import Utils from "@/tools";
  import NetworkArticle from "@/network/network_article";
  import CategoriesSelector from "@/components/categories_selector.svelte";
  import type { Category } from "@/types/articles/categories";
  import { validate_component, validate_each_argument } from "svelte/internal";

  /** articles loaded? */
  let loaded = false;
  /** article selected / overlay opened? */
  let toolsOverlay = false;
  /** selected article */
  let selected: {
    counter: number | null;
    article: Article | null;
  } = { counter: null, article: null };
  /** response articles */
  let articles: Record<number, Article> = {};
  /** response information */
  let meta: Meta;
  /** request params */
  let requestParams: Params = {
    page: 1,
    show: Show.published,
    by: By.updated,
    start: Start.newest,
    preview: true,
    category_name: null,
    without_category: false,
  };
  /** custom categories for filter */
  const customCategories: Record<number, Category> = {
    "-1": {
      id: "-1",
      name: "All",
    },
  };

  //////////// PARAMS TEST
  let urlParams: URLSearchParams;
  const queryUnsub = querystring.subscribe((val) => {
    urlParams = new URLSearchParams(val);
  });

  onMount(async () => {
    await queryStringToRequestParams();
    await getAll(undefined);
  });

  //////////// PARAMS TEST
  // TODO: validate requestParams before send to server, 
  // changed querystring if sort changed
  async function queryStringToRequestParams() {
    if (!urlParams) {
      return;
    }
    return new Promise((resolve) => {
      urlParams.forEach((key, name) => {
        console.log(name, key)
        if (!requestParams[name]) {
          return;
        }
        console.log('e')
        requestParams[name] = key;
      });
      resolve(true);
    });
  }

  // const newURL =
  //   window.location.protocol +
  //   "//" +
  //   window.location.host +
  //   window.location.pathname +
  //   "?myNewUrlQuery=1";

  // window.history.pushState({ path: newURL }, "", newURL);
  ///////////////////////

  onDestroy(() => {
    queryUnsub();
  });

  /** get all articles.
   * @param p request params
   */
  async function getAll(p: Params = requestParams) {
    // trigger reactivity because baseParams may have been changed by history
    requestParams = requestParams;
    if (p.page < 1) {
      p.page = 1;
      requestParams.page = 1;
    }
    loaded = false;
    try {
      const result = await NetworkArticle.getAll(p);
      articles = result.data;
      meta = result.meta;
      loaded = true;
    } catch (err) {}
  }

  /** edit article */
  function edit(counter: number) {
    const articleID = getIDByCounter(counter);
    push(`/articles/create/${articleID}`);
  }

  /** select article */
  function select(counter: number) {
    toolsOverlay = true;
    selected.counter = counter;
    selected.article = articles[counter];
  }

  /** publish article */
  async function publish(counter: number) {
    const converted = getIDByCounter(counter);
    toolsOverlay = false;
    try {
      await NetworkArticle.publish(converted);
      await deleteFromArray(counter);
    } catch (err) {}
  }

  /** unpublish article */
  async function unpublish(counter: number) {
    const converted = getIDByCounter(counter);
    toolsOverlay = false;
    try {
      await NetworkArticle.unpublish(converted);
      await deleteFromArray(counter);
    } catch (err) {}
  }

  /** delete article */
  async function deleteArticle(counter: number) {
    const isDelete = await window.$choose.confirm("delete article");
    if (!isDelete) {
      return;
    }
    toolsOverlay = false;
    try {
      const converted = getIDByCounter(counter);
      await NetworkArticle.delete(converted);
      await deleteFromArray(counter);
    } catch (err) {}
  }

  /** delete article from articles array and refresh articles */
  async function deleteFromArray(counter: number) {
    delete articles[counter];
    articles = articles;
    await refresh();
  }

  /** set 'by' param and get articles */
  function setBy(by: By = By.published) {
    requestParams.by = by;
    requestParams.page = 1;
    getAll();
  }

  /** set 'start' param and get articles */
  function setStart(start: Start = Start.newest) {
    requestParams.start = start;
    requestParams.page = 1;
    getAll();
  }

  /** set 'show' param and get articles */
  function setShow(show: Show) {
    requestParams.show = show;
    requestParams.page = 1;
    getAll();
  }

  /** when page changed */
  function onPageChanged(page: number) {
    requestParams.page = page;
    getAll();
  }

  /** get article id by articles counter id */
  function getIDByCounter(counter: number): string {
    return articles[counter].id;
  }

  /** refresh articles */
  async function refresh() {
    while (true) {
      const articlesLength = Utils.getObjectLength(articles);
      const noArticles = loaded && articlesLength < 1;
      if (!noArticles) {
        break;
      }
      requestParams.page--;
      try {
        await getAll();
      } catch (err) {
        break;
      }
      if (requestParams.page < 2) {
        break;
      }
    }
  }

  /** sort by category */
  function onCategoryChanged(cat: Category | null) {
    requestParams.page = 1;
    // no categories
    requestParams.without_category = cat === null;
    let catName = null;
    const notAllCategories = cat && cat["name"] && cat.id !== "-1";
    if (notAllCategories) {
      catName = cat.name;
    }
    requestParams.category_name = catName;
    getAll();
  }
</script>

<div class="articles base__container">
  <div class="toolbars">
    <ToolbarBig>
      <a href="#/articles/create">new</a>
      <a href="#/articles/cats">categories</a>
    </ToolbarBig>

    <Toolbar>
      <CategoriesSelector
        {customCategories}
        selectedID={"-1"}
        on:changed={(e) => onCategoryChanged(e.detail)}
      />
    </Toolbar>

    <Toolbar>
      <div class="articles__item">
        {#if requestParams.show === Show.published}
          <div class="pointer" on:click={() => setShow(Show.drafts)}>
            published
          </div>
        {/if}
        {#if requestParams.show === Show.drafts}
          <div class="pointer" on:click={() => setShow(Show.published)}>
            drafts
          </div>
        {/if}
      </div>
      <div class="articles__item">
        {#if requestParams.start === Start.newest}
          <div class="pointer" on:click={() => setStart(Start.oldest)}>
            newest
          </div>
        {/if}
        {#if requestParams.start === Start.oldest}
          <div class="pointer" on:click={() => setStart(Start.newest)}>
            oldest
          </div>
        {/if}
      </div>
      <div class="articles__item">
        {#if requestParams.by === By.updated}
          <div class="pointer" on:click={() => setBy(By.published)}>
            by updated date
          </div>
        {/if}
        {#if requestParams.by === By.published}
          <div class="pointer" on:click={() => setBy(By.created)}>
            by published date
          </div>
        {/if}
        {#if requestParams.by === By.created}
          <div class="pointer" on:click={() => setBy(By.updated)}>
            by created date
          </div>
        {/if}
      </div>
    </Toolbar>
  </div>

  <div class="list">
    {#if articles}
      {#each Object.entries(articles) as [id, article]}
        <CArticle {article} on:selected={(e) => select(parseInt(id, 10))} />
      {/each}
    {/if}
  </div>

  <div class="pages">
    {#if meta}
      <Pagination
        total={meta.total_pages}
        current={meta.current_page}
        on:changed={(e) => onPageChanged(e.detail)}
      />
    {/if}
  </div>

  {#if toolsOverlay}
    <Overlay onClose={() => (toolsOverlay = false)}>
      <div class="overlay">
        {#if selected && selected.article.is_published}
          <div
            class="overlay__item"
            on:click={() => unpublish(selected.counter)}
          >
            unpublish
          </div>
        {:else}
          <div class="overlay__item" on:click={() => publish(selected.counter)}>
            publish
          </div>
        {/if}
        <div class="overlay__item" on:click={() => edit(selected.counter)}>
          edit
        </div>
        <div
          class="overlay__item"
          on:click={() => deleteArticle(selected.counter)}
        >
          delete
        </div>
      </div>
    </Overlay>
  {/if}
</div>

<style lang="scss">
  .toolbars {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .overlay {
    width: 100%;
    display: flex;
    flex-direction: column;
    &__item {
      height: 64px;
      width: 100%;
      font-size: 1rem;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    &__item:hover {
      background-color: var(--color-hover);
    }
  }
</style>

// src/elvenfront/src/views/articles/Articles.vue
<template>
  <div class="articles__container">
    <div class="articles__create">
      <RouterLink :to="{ name: 'ArticleCreate' }">create</RouterLink>
    </div>
    <div class="articles__toolbar">
      <div class="articles__show">
        <div
          class="articles__item articles__show-published"
          v-if="show === 'published'"
          v-on:click="getArticles(undefined, 'drafts')"
        >show published</div>
        <div
          class="articles__item articles__show-drafts"
          v-if="show === 'drafts'"
          v-on:click="getArticles(undefined, 'published')"
        >show drafts</div>
      </div>
      <div class="articles__sort-by-date">
        <div
          class="articles__item"
          v-if="sortFirst === 'newest'"
          v-on:click="setSortDate('oldest')"
        >newest</div>
        <div
          class="articles__item"
          v-if="sortFirst === 'oldest'"
          v-on:click="setSortDate('newest')"
        >oldest</div>
      </div>
      <div class="articles__sort-by">
        <div
          class="articles__item"
          v-if="sortBy === 'updated'"
          v-on:click="setSort('published')"
        >by updated date</div>
        <div
          class="articles__item"
          v-if="sortBy === 'published'"
          v-on:click="setSort('created')"
        >by published date</div>
        <div
          class="articles__item"
          v-if="sortBy === 'created'"
          v-on:click="setSort('updated')"
        >by created date</div>
      </div>
    </div>

    <ArticlesList :articles="articles" @selected="selectArticle($emit)"></ArticlesList>

    <div class="articles__404" v-if="isArticlesLoaded && articles.length < 1">
      <div>no articles :(</div>
    </div>

    <Pagination
      :total-pages="totalPages"
      :current-page="currentPage"
      v-on:changed="getArticles($event)"
    ></Pagination>
  </div>

  <Overlay v-bind:active="isToolsOverlayActive" v-on:deactivated="isToolsOverlayActive = false">
    <!-- tools -->
    <div class="overlay__article-manage" v-if="isToolsOverlayActive">
      <div
        class="overlay__item make__draft"
        v-if="selectedArticle && selectedArticle.is_published"
        v-on:click="makeDraftArticle(selectedArticle)"
      >make a draft</div>
      <div class="overlay__item publish" v-else v-on:click="publishArticle(selectedArticle)">publish</div>
      <div class="overlay__item edit" v-on:click="editArticle(selectedArticle)">edit</div>
      <div class="overlay__item delete" v-on:click="deleteArticle(selectedArticle)">delete</div>
    </div>
  </Overlay>
</template>

<script setup lang="ts">
import { onMounted, ref, Ref } from "@vue/runtime-core"
import { useRouter } from "vue-router"
import { IArticle } from "@/types/article"
import { IMeta } from "@/types/global"
import ArticleAdapter from "@/common/adapters/Main/ArticleAdapter"
import Overlay from "@/components/ui/Overlay.vue"
import Pagination from "@/components/ui/Pagination.vue"
import ArticlesList from "@/components/parts/ArticlesList.vue"

const router = useRouter()
// service
const isArticlesLoaded = ref(false)
const isToolsOverlayActive = ref(false)
const selectedArticle: Ref<IArticle | null> = ref(null)
// articles
const articles: Ref<Array<IArticle>> = ref([])
const articlesMeta: Ref<IMeta | null> = ref(null)
// params
const show = ref('published')
const sortBy = ref('updated')
const sortFirst = ref('newest')
// pagination
const page = ref(1)
const perPage = ref(1)
const totalPages = ref(1)
const currentPage = ref(1)

onMounted(async () => {
  await getArticles()
})

async function getArticles(pageA = page.value, showA = show.value, sortByA = sortBy.value, sortFirstA = sortFirst.value) {
  page.value = pageA
  show.value = showA
  console.log(show.value)
  sortBy.value = sortByA
  sortFirst.value = sortFirstA
  isArticlesLoaded.value = false
  ArticleAdapter.getArticles(pageA, showA, sortByA, sortFirstA)
    .then(async result => {
      articles.value = result.data
      articlesMeta.value = result.meta
      perPage.value = articlesMeta.value.per_page
      currentPage.value = articlesMeta.value.current_page
      totalPages.value = articlesMeta.value.total_pages
      isArticlesLoaded.value = true
    })
}

async function editArticle(article) {
  await router.push({ name: 'ArticleCreate', params: { id: article.id } })
}

async function deleteArticle(article) {
  const isDelete = confirm('Удалить запись?')
  if (isDelete) {
    await ArticleAdapter.deleteArticle(article.id)
    deleteArticleFromArray(article)
    isToolsOverlayActive.value = false
    refreshArticles()
  }
}

async function publishArticle(article) {
  await ArticleAdapter.publishArticle(article)
    .then(() => {
      deleteArticleFromArray(article)
      isToolsOverlayActive.value = false
    })
  refreshArticles()
}

async function makeDraftArticle(article) {
  await ArticleAdapter.makeDraftArticle(article)
    .then(() => {
      deleteArticleFromArray(article)
      isToolsOverlayActive.value = false
    })
  refreshArticles()
}

async function refreshArticles() {
  // refresh is need when for ex. you deleted all articles on current page
  // and we need to check, is data on current page exists?
  // if page > 1 and no data, we moving back (currentPage--) and get new articles
  let notArticles = isArticlesLoaded.value && articles.value.length < 1
  console.log(notArticles)
  if (notArticles) { // no articles in current page
    while (notArticles) {
      // moving back until the pages ends or data appears
      currentPage.value--
      await getArticles()
      if (currentPage.value <= 1) {
        break
      }
      notArticles = isArticlesLoaded.value && articles.value.length < 1
    }
  }
}


async function setSort(sort) {
  sortBy.value = sort
  page.value = 1
  await getArticles()
}
async function setSortDate(age = 'newest') {
  sortFirst.value = age
  page.value = 1
  await getArticles()
}

function deleteArticleFromArray(article) {
  const index = articles.value.indexOf(article)
  articles.value.splice(index, 1)
  return true
}

function selectArticle(article) {
  isToolsOverlayActive.value = true
  selectedArticle.value = article
}

</script>

<style scoped>
.articles__container {
  width: 95%;
  height: 100%;
  max-width: 512px;
  margin: auto;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.articles__create {
  background-color: var(--color-level-1);
  height: 36px;
  width: 100%;
  display: flex;
  flex-direction: row;
}

.articles__create > a {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
}

.articles__create > a:hover {
  background-color: var(--color-hover);
}

.articles__toolbar {
  background-color: var(--color-level-1);
  padding-left: 12px;
  font-size: 0.8rem;
  min-height: 36px;
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 12px;
  font-weight: bold;
}

.articles__item {
  cursor: pointer;
}

.articles__404 {
  background-color: var(--color-level-1);
  height: 240px;
  border-radius: var(--border-radius);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 24px;
}

.overlay__article-manage,
.overlay__articles-sort {
  width: 100%;
  display: flex;
  flex-direction: column;
}

.overlay__item {
  height: 64px;
  width: 100%;
  font-size: 1rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}

.overlay__item:hover {
  background-color: var(--color-hover);
}
</style>
