// src/elven/src/views/articles/ArticleCreate.svelte
<script lang="ts">
  import EditorJS from "@editorjs/editorjs"
  import Head from "@editorjs/header"
  import ImageTool from "@editorjs/image"
  import ArticleAdapter from "@/common/adapters/Main/ArticleAdapter"
  import type TextareaResizer from "@/common/tools/TextareaResizer"
  import type { IArticle } from "@/types/article"
  import Overlay from "@/components/ui/Overlay.svelte"
  import { onDestroy, onMount } from "svelte"

  export let article: IArticle = {
    id: "",
    user_id: "",
    is_published: false,
    title: "",
    content: null,
    slug: "",
    published_at: "",
    updated_at: "",
  };
  export let timeoutID: ReturnType<typeof setTimeout> | null = null;
  export let editorTimeoutID: ReturnType<typeof setTimeout> | null = null;
  export let editorLoadAttempts = 0;
  export let isEditorInitialized = false;
  export let isErrorOverlayActive = false;
  export let errorOverlayContent = "";
  let textareaResizer: TextareaResizer;

  onMount(async () => {
    // const route = useRoute();
    // let id = null;
    // if (route.params.id) {
    //   id = route.params.id.toString();
    // }
    // await initEditor();
    // if (id) {
    //   article.id = id;
    //   const isSuccess = await initEditArticle();
    //   if (isSuccess) {
    //     await setEditorData();
    //   } else {
    //     isEditorInitialized = true;
    //   }
    // } else {
    //   isEditorInitialized = true;
    // }
    // textareaResizer = new TextareaResizer("article-title");
    // textareaResizer.start();
  });

  onDestroy(async () => {
    await window.editor.destroy();
    textareaResizer.destroy();
    if (editorTimeoutID) {
      clearTimeout(editorTimeoutID);
    }
  });

  function initEditor() {
    window.editor = new EditorJS({
      holder: "editor",
      tools: {
        paragraph: {
          config: {
            placeholder: `It's a long story.`,
          },
        },
        header: {
          class: Head,
          inlineToolbar: true,
          config: {
            placeholder: "Header",
            levels: [2, 3, 4],
            defaultLevel: 3,
          },
        },
        image: {
          class: ImageTool,
          config: {
            endpoints: {
              byFile: "http://localhost:8008/uploadFile", // Your backend file uploader endpoint
              byUrl: "http://localhost:8008/fetchUrl", // Your endpoint that provides uploading by Url
            },
          },
        },
      },
      minHeight: 0,
      data: {},
    });
  }

  async function autoSave() {
    if (!isEditorInitialized) {
      throw Error("editor not initialized");
    }
    if (timeoutID && timeoutID) {
      clearTimeout(timeoutID);
    }
    timeoutID = setTimeout(async () => {
      let saveAllowed = false;
      await window.editor.save().then((outputData) => {
        if (outputData.blocks.length >= 1) {
          saveAllowed = true;
          article.content = outputData;
        }
      });
      if (!saveAllowed) {
        return;
      }
      if (article.id.length < 1) {
        await ArticleAdapter.createArticle(article).then((newArticle) => {
          article.id = newArticle.id;
        });
      } else {
        await ArticleAdapter.saveArticle(article);
      }
    }, 1000);
  }

  async function initEditArticle() {
    if (article.id.length < 1) {
      return Promise.resolve(false);
    }
    try {
      const result = await ArticleAdapter.getArticle(article.id);
      article = result;
      return Promise.resolve(true);
    } catch (err) {
      if (err === 404) {
        errorOverlayContent =
          "Article not found. You are redirected to create a new article.";
      } else {
        errorOverlayContent = `Strange error: ${err}`;
      }
      article.id = "";
      await router.push({ name: "ArticleCreate" });
      isErrorOverlayActive = true;
      return Promise.resolve(false);
    }
  }

  async function setEditorData() {
    editorTimeoutID = setInterval(async () => {
      if (editorLoadAttempts > 20) {
        isEditorInitialized = false;
        clearInterval(editorTimeoutID);
        throw Error(
          "failed while trying load data to editor. Is internet down? Server problems? Or article content have bad format, like bad/not JSON parsed."
        );
      }
      try {
        if (article.id.length < 1) {
          clearInterval(editorTimeoutID);
          return;
        }
        await window.editor.render(article.content);
        isEditorInitialized = true;
        clearInterval(editorTimeoutID);
      } catch (err) {
        console.info(`Trying to load data in editor... Last error: ${err}`);
        editorLoadAttempts++;
      }
    }, 500);
  }
</script>

<main>
  <div class="articles-create-container">
    <div class="articles-create-main">
      <textarea
        id="article-title"
        placeholder="Actually..."
        rows="1"
        maxlength="124"
        v-model="article.title"
        on:input={autoSave}
      />
      <div class="editor-container">
        <div id="editor" on:input={autoSave} />
      </div>

      <Overlay
        v-bind:active="isErrorOverlayActive"
        v-on:deactivated="isErrorOverlayActive = false"
      >
        {{ errorOverlayContent }}
        <div
          class="error-ok-button"
          on:click={() => (isErrorOverlayActive = false)}
        >
          Ок
        </div>
      </Overlay>
    </div>
  </div>
</main>

<style>
  .articles-create-container {
    max-width: 732px;
    margin: auto;
    background-color: var(--color-level-1);
    border-radius: 6px;
    padding-bottom: 24px;
  }

  @media screen and (max-width: 1919px) {
    .articles-create-container {
      width: 95%;
      max-width: 512px;
    }
  }

  .articles-create-main {
    width: 85%;
    height: 95%;
    margin: auto;
    display: flex;
    flex-direction: column;
    gap: 24px;
  }

  #article-title {
    margin-top: 12px;
    min-height: 38px;
    text-indent: 0;
    border: none;
    background-color: transparent;
    font-size: 1.6rem;
    font-weight: bold;
  }

  .editor-container {
    width: 100%;
  }

  #editor {
    height: 100%;
  }

  .error-ok-button {
    border-radius: var(--border-radius);
    background-color: var(--color-text);
    width: 25%;
    height: 10%;
    color: var(--color-body);
    cursor: pointer;
    font-weight: bold;
    font-size: 1rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  @media screen and (max-width: 1023px) {
    .articles-create-main {
      width: 95%;
      height: 95%;
    }
  }
</style>

// src/elvenfront/src/views/Main/Articles/ArticleCreate.vue
<template>
  <div class="container">
    <Header></Header>
    <div class="content">
      <textarea id="article-title"
                placeholder="Если коротко..."
                rows="1"
                v-model="article.title"
                @input="autoSave">
      </textarea>
      <div class="editor-container">
        <div id="editor" @input="autoSave">
        </div>
      </div>
    </div>


    <UIOverlay v-bind:active="isErrorOverlayActive" v-on:deactivated="isErrorOverlayActive = false">
      {{ errorOverlayContent }}
      <div class="error-ok-button" v-on:click="isErrorOverlayActive = false">Ок</div>
    </UIOverlay>

  </div>
</template>

<script>
import {defineComponent} from "vue"
import {useRoute} from 'vue-router'
import Header from "@/components/Header/Header"
import EditorJS from '@editorjs/editorjs'
import Head from '@editorjs/header'
import ArticleAdapter from "@/common/adapters/Main/ArticleAdapter"
import UIOverlay from "@/components/_UI/UIOverlay"
import TextareaResizer from "@/common/tools/TextareaResizer"

export default defineComponent({
  name: 'ArticleCreate',
  components: {UIOverlay, Header},
  data() {
    return {
      article: {
        id: null,
        title: '',
        content: undefined,
      },
      timeoutID: undefined,
      editorTimeoutID: undefined,
      editorLoadAttempts: 0,
      isEditorInitialized: false,
      isErrorOverlayActive: false,
      errorOverlayContent: '',

      textareaResizer: undefined,
    }
  },
  async mounted() {
    const route = useRoute()
    const id = route.params.id
    await this.initEditor()
    if (id) {
      this.article.id = id
      const isSuccess = await this.initEditArticle()
      if (isSuccess) {
        await this.setEditorData()
      } else {
        this.isEditorInitialized = true
      }
    } else {
      this.isEditorInitialized = true
    }
    this.textareaResizer = new TextareaResizer('article-title')
    this.textareaResizer.start()
  },
  async unmounted() {
    await window.editor.destroy()
    this.textareaResizer.destroy()
  },
  methods: {
    async initEditor() {
      window.editor = new EditorJS({
        holder: 'editor',
        tools: {
          paragraph: {
            config: {
              placeholder: 'Если развернуто...'
            }
          },
          header: {
            class: Head,
            inlineToolbar: true,
            config: {
              placeholder: 'Заголовок',
              levels: [2, 3, 4],
              defaultLevel: 3
            }
          },
        },
        minHeight: 0,
        data: {}
      })
    },
    async autoSave() {
      if (!this.isEditorInitialized) {
        throw Error('editor not initialized.')
      }
      if (this.timeoutID) {
        clearTimeout(this.timeoutID)
      }
      this.timeoutID = setTimeout(async () => {
        let saveAllowed = false
        await window.editor.save().then((outputData) => {
          if (outputData.blocks.length >= 1) {
            saveAllowed = true
            this.article.content = outputData
          }
        })
        if (!saveAllowed) {
          return 0
        }
        if (!this.article.id) {
          await ArticleAdapter.createArticle(this.article)
              .then(article => {
                this.article.id = article.id
              })
        } else {
          await ArticleAdapter.saveArticle(this.article)
        }
      }, 1000)
    },
    // ARTICLE EDITING FUNCTIONS START //
    async initEditArticle() {
      return await ArticleAdapter.getArticle(this.article.id)
          .then((article) => {
            this.article = article
            return Promise.resolve(true)
          })
          .catch(async (error) => {
            if (error === 404) {
              console.log('Запись не найдена')
              this.errorOverlayContent = 'Вы хотите отредактировать запись, которой не существует. Мы перенаправили вас на создание новой записи.'
            } else {
              this.errorOverlayContent = `Произошла странная ошибка. Ошибка: ${error}`
            }
            this.article.id = undefined
            await this.$router.push({name: 'ArticleCreate'})
            this.isErrorOverlayActive = true
            return Promise.resolve(false)
          })
    },
    async setEditorData() {
      this.editorTimeoutID = setInterval(async () => {
        if (this.editorLoadAttempts > 20) {
          this.isEditorInitialized = false
          clearInterval(this.editorTimeoutID)
          throw Error('failed while trying load data to editor. Is internet down? Server problems? Or article content have bad format, like bad/not JSON parsed.')
        }
        try {
          await window.editor.render(JSON.parse(this.article.content))
          this.isEditorInitialized = true
          clearInterval(this.editorTimeoutID)
        } catch (err) {
          console.info('Trying to load data in editor...')
          this.editorLoadAttempts++
        }
      }, 500)
    },
    // ARTICLE EDITING FUNCTIONS END //
  },
})
</script>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 32px;
}

.content {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

#article-title {
  text-indent: 0;
  border: none;
  background-color: transparent;
  font-size: 1.6rem;
  font-weight: bold;
}

.editor-container {
  height: 100%;
}

#editor {
  height: 100%;
}

.error-ok-button {
  border-radius: 6px;
  background-color: var(--color-text);
  width: 25%;
  height: 10%;
  color: var(--color-body);
  cursor: pointer;
  font-weight: bold;
  font-size: 1rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>
